name: 'Skript Tests'
description: 'Runs Skript tests'
inputs:
  test_script_directory:
    description: 'The directory containing the tests to run'
    required: true
  skript_repo_ref:
    description: 'The Git reference of the Skript version to test with (this can be a commit sha, branch, tag, etc.)'
    required: false
  run_vanilla_tests:
    description: 'Controls whether or not the vanilla Skript tests are run. It is recommended you keep this on to ensure your addon doesn''t change vanilla behavior'
    required: false
    default: 'true'
  extra_plugins_directory:
    description: 'The directory containing the plugins to install on the test server alongside Skript'
    required: false

#outputs:
#  passed:
#    description: 'Whether or not the tests passed'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-script-directory }}
    - ${{ inputs.skript-repo-ref }}
    - ${{ inputs.run-vanilla-tests }}
