name: 'Skript Tests'
description: 'Runs Skript tests'
inputs:
  test_script_directory:
    description: 'The directory containing the tests to run'
    required: true
  skript_repo:
    description: 'The Skript repository to clone'
    required: false
    default: 'SkriptLang/Skript'
  skript_repo_ref:
    description: 'The Git reference of the Skript version to test with (this can be a commit sha, branch, tag, etc.)'
    required: false
    default: master
  run_vanilla_tests:
    description: 'Controls whether or not the vanilla Skript tests are run. It is recommended you keep this on to ensure your addon doesn''t change vanilla behavior'
    required: false
    default: 'true'
  extra_plugins_directory:
    description: 'The directory containing the plugins to install on the test server alongside Skript'
    required: false

#outputs:
#  passed:
#    description: 'Whether or not the tests passed'

runs:
  using: 'composite'
  steps:
    - name: Checkout Skript
      uses: actions/checkout@v4
      with:
        path: skript
        repository: ${{ inputs.skript-repo }}
        submodules: recursive
    - name: Compute current Skript HEAD
      id: skript-sha
      shell: bash
      run: echo "head_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: Cache Skript build
      uses: actions/cache@v4
      id: cache-skript
      with:
        path: build
        key: "skript-${{ steps.skript-sha.outputs.head_sha }}"
    - name: Build Skript
      if: steps.cache-skript.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew quickTest
    - name: Cache test image
      uses: ScribeMD/docker-cache@0.5.0
      id: cache-image
      with:
        # Remember to change the image tag in all places!
        key: "test-image-3fafa20"
    - name: Pull test image
      shell: bash
      # Remember to change the image tag in all places!
      run: "docker pull ghcr.io/skriptlang/skript-test-action:3fafa20"
      if: steps.cache-skript.outputs.cache-hit != 'true'
    - name: Run tests
      shell: bash
      # Remember to change the image tag in all places!
      run: "docker run -a -v /github/workspace:/github/workspace ghcr.io/skriptlang/skript-test-action:3fafa20"
